### PR TITLE
Formatting export CSV column headers Bug

### PR DESCRIPTION
**Pull request by shahidulkareem**
We have fixed export CSV column headers issue. Please look at second commit changes

### CODE REVIEW

**Comment by filipdanic** [comment]
Thanks for PR, 🎉 I’ll have a look at it today.

**Comment by shahidulkareem** [comment]
Ok thank you

**Comment by filipdanic** [comment]
Your branch is no up to date with the master branch. Luckily, there are no conflicts. I’ll merge them and test things out.

**Comment by filipdanic** [comment]
Live in `spicy-datatable@0.8.1`

**Pull request merged**
